### ISSUE TITLE
Thumbor 7.2.0

### ISSUE THREAD

**Issue by panki3a** [mvhirsch/thumbor-docker#13]
Hi,
Can you look at https://thumbor.readthedocs.io/en/latest/format.html new version of thumobr 7.2.0 ?
They realise it with new AVIF format.
Thanks.

**Comment by mvhirsch** [comment]
Since the configuration file got updated and some more packages (like `color`) need attention, I need to update many part of the Dockerimage which needs time. If you want to steep up things, please provide a PR :+1:

**Comment by panki3a** [comment]
I can help with testing with new version, but I dont have skils to make new version of Docker image :)

**Comment by panki3a** [comment]
there is 7.5.2 relese

**Comment by mvhirsch** [comment]
> there is 7.5.2 relese

Yes. I just released it :+1:
