### ISSUE TITLE
AUTO AVIF

### ISSUE THREAD

**Issue by panki3a** [mvhirsch/thumbor-docker#15]
in 7.5.2 , is there ENV variable "AUTO_AVIF" similar to "AUTO_WEBP" ?

**Comment by mvhirsch** [comment]
Looks like the `AUTO_AVIF` is missing in thumbor.conf.tpl, while [thumbor added the configuration](https://github.com/thumbor/thumbor/blob/7.5.2/thumbor/thumbor.conf#L41-L43). 

I must admit, I blindly trusted https://github.com/mvhirsch/thumbor-docker/pull/14#issuecomment-1640827880. 
Because of the current version scheme, I may not update the tags to not break things in wild. But I'll provide a bugfix in next version.

In the meantime, you may add a file containing the AUTO_AVIF option like this:

```
# ./avif.conf
echo "AUTO_AVIF = True" >> /usr/local/thumbor/thumbor.conf
```

```bash
docker run --rm -v ./avif.conf:/docker-entrypoint.d/avif.conf mvhirsch/thumbor:7.5.2
```

**Comment by panki3a** [comment]
thanx, i will try this

**Comment by panki3a** [comment]
i test it,
i looked into " cat /usr/local/thumbor/thumbor.conf"
and there is **AUTO_AVIF = True**
Bud image is not autoconverted into AVIF
![image](https://github.com/mvhirsch/thumbor-docker/assets/16493179/98e585b9-d4ce-4f9f-a60d-beeb55b26d8c)
Any idea, what can i do for using AUTO AVIF ?

**Comment by mvhirsch** [comment]
>  Any idea, what can i do for using AUTO AVIF ?

Hows the request sent? Did it use `Accept: image/avif`?
Which docker image did you use?

**Comment by panki3a** [comment]
Yes, it has,
![image](https://github.com/mvhirsch/thumbor-docker/assets/16493179/15c829e7-500a-4a65-aba1-992713c541d0)

**Comment by mvhirsch** [comment]
Which docker image do you use?

**Comment by panki3a** [comment]
mvhirsch/thumbor:7.5.2-alpine

**Comment by mvhirsch** [comment]
Thanks. After reading the documentation, it looks like `AUTO_AVIF` needs pillow-avif-plugin which is not installead on alpine image: https://github.com/thumbor/thumbor/blob/4c86c232dfb5bf2b1b8a849ae90d813113b2aba1/thumbor/thumbor.conf#L42

You need to install the plugin first. This is not supported by mvhirsch/thumbor-docker.

**Comment by panki3a** [comment]
how can I install it ?
Can i do it in my own Dockerfile extended FROM mvhirsch/thumbor:7.5.2-alpine ?

**Comment by mvhirsch** [comment]
Of course you may extend the image. This might work (I didn't test it):

```
FROM mvhirsch/thumbor:7.5.2-alpine

RUN pip install pillow-avif-plugin
```

**Comment by panki3a** [comment]
ok, and how can i enable it, this plugin ?
Do i need add something into thumbor.conf ?
Thanx

**Comment by panki3a** [comment]
![image](https://github.com/mvhirsch/thumbor-docker/assets/16493179/45485d07-4ec4-40b3-87d8-21e801b70112)
Its only need to install plugin and now its working.
Thanx
