### ISSUE TITLE
Update 7.0.0

### ISSUE THREAD

**Issue by mvhirsch** [mvhirsch/thumbor-docker#5]
v7 just got released: https://github.com/thumbor/thumbor/releases/tag/7.0.0

Updating `slim` and `fundamentals` images, as well as building a new `alpine` version.

- [x] `slim`
- [x] `fundamentals` (`slim` + AWS storage, pngquant and mozjpeg)
- [x] alpine

**Comment by mvhirsch** [comment]
blocked by https://github.com/thumbor/thumbor-aws/issues/1

**Comment by mvhirsch** [comment]
Building opencv on alpine: https://github.com/czeni/opencv-video-minimal

- https://docs.opencv.org/4.x/d7/d9f/tutorial_linux_install.html
- https://docs.opencv.org/4.x/d2/de6/tutorial_py_setup_in_ubuntu.html

**Comment by heynemann** [comment]
This should be able to move forward now :) Added this project to [awesome-thumbor](https://github.com/thumbor/awesome-thumbor). Good job!

**Comment by mvhirsch** [comment]
> This should be able to move forward now

Definitely!

> Added this project to awesome-thumbor. Good job!

Thank you! :tada:
